### ISSUE TITLE
Option to be disabled when other applications in full screen

### ISSUE THREAD

**Issue by Riajyuu** [vhanla/winxcorners#13]
Just in case that this may interrupt something, e.g. gaming, video playing, PPT presenting and all that.

**Comment by vhanla** [comment]
This issue is currently on progress, see #6   
I already pushed `functions.pas` code which does detect DirectX and OpenGL procedure to detect full screen 3D applications. I hope I will release it soon, more testings are needed.

**Comment by Riajyuu** [comment]
yes, it is. thanks
