### ISSUE TITLE
custom command how to write like alt+tab or other with example

### ISSUE THREAD

**Issue by SKHasmukh** [vhanla/winxcorners#56]
can you give me the command for alt+esc key , so I can copy and paste it. It would be great if there is short video of how to write custom command. I am newbie, I tried writing my own but it did not work. Need I have to continuously switch between two windows One where I am working another for googling. Windows 11 Home edition amd ryzen 7 4800H. Thanks👏

_Originally posted by @SKHasmukh in https://github.com/vhanla/winxcorners/issues/52#issuecomment-2331172304_

**Comment by xeahsoon** [comment]
> ```
>           can you give me the command for alt+esc key , so I can copy and paste it. It would be great if there is short video of how to write custom command. I am newbie, I tried writing my own but it did not work. Need I have to continuously switch between two windows One where I am working another for googling. Windows 11 Home edition amd ryzen 7 4800H. Thanks👏
> ```
> 
> _Originally posted by @SKHasmukh in [#52 (comment)](https://github.com/vhanla/winxcorners/issues/52#issuecomment-2331172304)_

You can refer to this project, this is how I use it currently.：https://github.com/xeahsoon/keyboard-simulator
