### ISSUE TITLE
running notepad.exe behaves very strange

### ISSUE THREAD

**Issue by akamienski** [vhanla/winxcorners#65]
**Describe the bug**
I've assigned simple custom command to run notepad.exe. It runs it at first, but when I close notepad window, it doesn't actually ends the process. When I want to trigger it again, it creates separate notepad process, but doesn't show the window itself.

**Desktop (please complete the following information):**
 - Windows 11 Pro 24H2 26100.2605
 - WinXcorners 1.3.1

**Comment by vhanla** [comment]
Oh, I didn't notice the Launch hidden option is not correctly being assigned, thank you, I will fix it.

**Comment by akamienski** [comment]
@vhanla thanks, I've also noticed that all windows (task view) action does not turn off that view, if already shown and I touch the corner again, is this a design choice? as I think this can be done, at least in HotCornerWin it works like that.

**Comment by vhanla** [comment]
@akamienski I haven't tested on Windows 11, just Windows 10, I'll check that too.

**Comment by vhanla** [comment]
@akamienski I hope it is working as expected now. ![v1.3.2](https://github.com/vhanla/winxcorners/releases/tag/1.3.2) Although I noticed Notepad in Windows 11 is different than Windows 10, I suppose it now remembers unsaved buffers, and it triggered more instances as if the launch command was repeating when unsaved closing happened, like taskkill /f /im notepad.exe or reboot without saving 😅

**Comment by akamienski** [comment]
@vhanla works perfectly now, thank you!
